# Generated by Django 5.0.14 on 2026-03-07 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atendimento',
            name='data',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='atendimento',
            name='medicamentoso',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
