# Generated by Django 5.0.14 on 2026-03-07 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_atendimento_data_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='atendimento',
            options={'ordering': ['-data', '-criado_em'], 'verbose_name': 'Atendimento', 'verbose_name_plural': 'Atendimentos'},
        ),
        migrations.AlterModelOptions(
            name='cadete',
            options={'ordering': ['numero'], 'verbose_name': 'Cadete', 'verbose_name_plural': 'Cadetes'},
        ),
        migrations.AlterModelOptions(
            name='profissional',
            options={'ordering': ['tipo', 'identificador'], 'verbose_name': 'Profissional', 'verbose_name_plural': 'Profissionais'},
        ),
        migrations.AlterUniqueTogether(
            name='profissional',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='atendimento',
            name='alta',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='atendimento',
            name='atendimento',
            field=models.CharField(choices=[('inicial', 'Inicial'), ('retorno', 'Retorno')], db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='atendimento',
            name='criado_em',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='atendimento',
            name='fisioterapia',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='atendimento',
            name='lesao_tipo',
            field=models.CharField(blank=True, db_index=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='atendimento',
            name='parte_do_corpo',
            field=models.CharField(blank=True, db_index=True, max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='atendimento',
            name='profissional_tipo',
            field=models.CharField(blank=True, db_index=True, max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='cadete',
            name='ano',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='cadete',
            name='curso',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='cadete',
            name='numero',
            field=models.IntegerField(db_index=True, unique=True),
        ),
        migrations.AlterField(
            model_name='profissional',
            name='tipo',
            field=models.CharField(choices=[('medico', 'Médico'), ('fisioterapeuta', 'Fisioterapeuta'), ('educador_fisico', 'Educador Físico'), ('nutricionista', 'Nutricionista'), ('psicopedagogo', 'Psicopedagogo'), ('sred', 'S-RED'), ('enfermagem', 'Enfermagem/PM CC'), ('instrutor', 'Instrutor'), ('estatistico', 'Estatístico'), ('ti', 'Profissional de TI')], db_index=True, max_length=50),
        ),
        migrations.AddIndex(
            model_name='atendimento',
            index=models.Index(fields=['cadete', 'data'], name='idx_cadete_data'),
        ),
        migrations.AddIndex(
            model_name='atendimento',
            index=models.Index(fields=['data', 'profissional_tipo'], name='idx_data_profissional'),
        ),
        migrations.AddConstraint(
            model_name='profissional',
            constraint=models.UniqueConstraint(fields=('tipo', 'identificador'), name='profissional_tipo_identificador_unique'),
        ),
    ]
